#ifndef HTTP_STATUS_HPP
#define HTTP_STATUS_HPP

enum http_status_code_t
{
	HTTP_CONTINUE = 100,
	HTTP_SWITCH_PROT,
	HTTP_OK = 200,
	HTTP_CREATED,
	HTTP_ACCEPTED,
	HTTP_NON_AUTH_INF,
	HTTP_NO_CONTENT,
	HTTP_RESET_CONTENT,
	HTTP_PARTIAL_CONTENT,
	HTTP_MULTIPLE_CHOICES = 300,
	HTTP_MOVED_PERMANENTLY,
	HTTP_FOUND,
	HTTP_SEE_OTHER,
	HTTP_NOT_MODIFIED,
	HTTP_USE_PROXY,
	HTTP_TMP_REDIRECT,
	HTTP_BAD_REQUEST = 400,
	HTTP_UNAUTHORIZED,
	HTTP_PAYMENT_REQUIRED,
	HTTP_FORBIDDEN,
	HTTP_NOT_FOUND,
	HTTP_METHOD_NOT_ALLOWED,
	HTTP_NOT_ACCEPTABLE,
	HTTP_PROXY_AUTH_REQUIRED,
	HTTP_REQUEST_TIMEOUT,
	HTTP_CONFLICT,
	HTTP_GONE,
	HTTP_LENGTH_REQUIRED,
	HTTP_PRECONDITION_FAILED,
	HTTP_REQUEST_ENTITY_TOO_LARGE,
	HTTP_REQUEST_URI_TOO_LARGE,
	HTTP_UNSUPPORTED_MEDIA_TYPE,
	HTTP_REQUESTED_RANGE_NOT_SATISFIABLE,
	HTTP_EXPECTATION_FAILED,
	HTTP_INTERNAL_SERVER_ERROR = 500,
	HTTP_NOT_IMPLEMENTED,
	HTTP_BAD_GATEWAY,
	HTTP_SERVICE_UNAVAILABLE,
	HTTP_GATEWAY_TIMEOUT,
	HTTP_VERSION_NOT_SUPPORTED
};

#endif
